steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/stayonbeat-new', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/stayonbeat-new' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - stayonbeat-new
      - --image=gcr.io/$PROJECT_ID/stayonbeat-new
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated

images:
  - gcr.io/$PROJECT_ID/stayonbeat-new
