version: '3.8'

services:
  app:
    # The name for the running container
    container_name: traxplaya_app

    # Tells Docker Compose to build the image from the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile

    # Maps port 3000 on the host to port 3000 in the container
    ports:
      - '3000:3000'

    # Loads environment variables from the specified file into the container
    env_file:
      - ./.env.local

    # Restarts the container automatically if it stops, unless it was manually stopped.
    restart: unless-stopped

    # Ensures the 'db' service is started before the 'app' service
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: traxplaya_db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
